# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Francesco Vitucci
email: francescovitucci@gmail.com
description: Francesco Vitucci is a composer, electroacoustic performer and teacher based in Bari (IT). Ordinary member of S.I.M.C. (Italian Society of Contemporary Music), his works are performed in concerts and contemporary music festivals, in Italy and abroad, and have been positively evaluated in various national and international composition competitions.
baseurl: "/francescovitucci" # the subpath of your site, e.g. /blog
url: "https://francescovitucci.com" # the base hostname & protocol for your site, e.g. http://example.com

facebook_path: https://www.facebook.com/fr.vitucci/
instagram_path: https://www.instagram.com/fr.vitucci/
youtube_path: https://www.youtube.com/@FrancescoVitucciComposer
github_path: https://github.com/fv-c

# Build settings
permalink: pretty
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
