title: Francesco Vitucci
email: info@francescovitucci.com
description: Francesco Vitucci is a composer, electroacoustic performer and teacher based in Bari (IT). Ordinary member of S.I.M.C. (Italian Society of Contemporary Music), his works are performed in concerts and contemporary music festivals, in Italy and abroad, and have been positively evaluated in various national and international composition competitions.
url: "https://www.francescovitucci.com"

facebook_path: https://www.facebook.com/fr.vitucci/
instagram_path: https://www.instagram.com/fr.vitucci/
youtube_path: https://www.youtube.com/@FrancescoVitucciComposer
github_path: https://github.com/fv-c
linkedin_path: https://www.linkedin.com/in/francesco-vitucci/

blogImgBin_path: /assets/img/blog/

# Build settings
permalink: pretty
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyllbuild.sh
  - lilypondprocess.py

sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier

jekyll-archives:
  enabled:
    - year
    - categories
  layout: archive
  permalinks:
    year: '/:year/'
    category: '/category/:name/'

jekyll-minifier:
  uglifier_args:
    harmony: true

