title: Francesco Vitucci
email: info@francescovitucci.com
description: Francesco Vitucci - Home.
url: "https://www.francescovitucci.com"

facebook_path: https://www.facebook.com/fr.vitucci/
instagram_path: https://www.instagram.com/fr.vitucci/
youtube_path: https://www.youtube.com/@FrancescoVitucciComposer
github_path: https://github.com/fv-c
linkedin_path: https://www.linkedin.com/in/francesco-vitucci/

blogImgBin_path: /assets/img/blog/

# Blog Images main resolution: height 650px
# Blog Images low resolution: height 200px
#
# Photo Images main resolution: height 1875px x 1000px
#
# Works Images resolution: height 3750px x 2000px

# Build settings
permalink: pretty
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyllbuild.sh
  - lilypondprocess.py
  - README.md

sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - categories
  layout: archive
  permalinks:
    year: "/:year/"
    category: "/category/:name/"
